# Generated by Django 5.0.3 on 2024-03-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
